language: shell
sudo: required
dist: xenial

branches:
  only:
    - github

os:
  - linux

install:
  - ./build.sh

script:
  - bash -c 'shopt -s globstar; shellcheck --exclude=SC2086 --exclude=SC2143 --exclude=SC2001 --exclude=SC2236 build.sh lint.sh'
