language: shell
sudo: required
dist: xenial

git:
  submodules: true

branches:
  only:
    - github

os:
  - linux

install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository universe
  - sudo ./build.sh
